### PR TITLE
created react app

### PR DESCRIPTION
**Pull request by themonster2015**

### CODE REVIEW

**Review by rvvergara — CHANGES_REQUESTED** [review]
## Hello @themonster2015,

### something's weird on the `stickler.yml` and `eslint.config` files :scream: 

I don't know if this was just an oversight or we thought we should place some html files on the [stickler](https://github.com/themonster2015/calculator/blob/206a920771be785b930db89961a6c128bea30204/stickler.yml) and [eslint.config](https://github.com/themonster2015/calculator/blob/206a920771be785b930db89961a6c128bea30204/eslint.config) files.

Whatever the cause of this absolute weirdness, let's fix it :)

## Let us delete the unnecessary files:

- `index.css`
- `App.test.js`
- `logo.svg`
- `serviceWorker.js`

Kindly implement these changes and resubmit a code review request for this milestone.

**Comment by themonster2015** [comment]
Thanks for reviewing my files. I have made the necessary deletions.

**Review by rvvergara — CHANGES_REQUESTED** [review]
## Hi @themonster2015,

### Great job cleaning up the directory from unnecessary files.

## BUT :scream: 
Our [`stickler.yml`](https://github.com/themonster2015/calculator/blob/6430b9e88830e1bb6e2bc918576186beac144fe7/stickler.yml#L7) and [`eslint.config`](https://github.com/themonster2015/calculator/blob/6430b9e88830e1bb6e2bc918576186beac144fe7/eslint.config#L7) files aren't fixed yet. We might have overlooked them. Let us please fix these before we can move on.

**Review by rvvergara — APPROVED** [review]
### Great!!! Now we can merge this branch into `development`

# :+1:

**Pull request merged**
